### ISSUE TITLE
Search Icon Image Link Broken

### ISSUE THREAD

**Issue by riyan-ahmed** [aeimaan/google-homepage#1]
![searchicon](https://user-images.githubusercontent.com/25188689/119276228-b301a100-bbe7-11eb-85d3-ceb1d315dfed.PNG)

The link to the search icon is broken. 

It should look like this
![search_icon_fixed](https://user-images.githubusercontent.com/25188689/119276247-d6c4e700-bbe7-11eb-966c-37656dc62982.PNG)

Maybe add the favicon to the source directory or use a link on the internet for one

**Comment by aeimaan** [comment]
Oh I didn’t realize that the link broke, I’ll fix it later tonight.
Thanks for letting me know

**Comment by aeimaan** [comment]
should be good now.
